[build]
  # Base directory for the build
  base = "/"
  # Directory containing the deploy-ready files
  publish = "dist"
  # Build command
  command = "npm run build"
  # Directory to change to before starting a build
  working_dir = "/"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # NPM version (optional, uses default if not specified)
  NPM_VERSION = "10.2.4"
  # Enable build plugins
  NETLIFY_USE_YARN = "true"
  # Configure build caching
  NETLIFY_CACHE_DIRECTORY = ".netlify/cache/"

# Redirects configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = "all"}

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.supabase.co; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.supabase.co;"

# Caching rules
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (these should be set in Netlify UI)
[build.environment]
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""

# Build plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  framework = "vite"
  targetPort = 5173
  publish = "dist"
  command = "npm run dev"
